config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :contacts
  get 'home/index'
  root to: 'home#index'

  resources :roles
  resources :job_titles
  resources :localities
  resources :suburbs
  resources :cities
  resources :regions
  resources :contats

  devise_scope :user do
    get '/users/sign_up' => 'users#sign_in'
  end

   get '/users' => 'users#index'

  get '/users/new' => 'users#new', :as => 'new_user'
  post 'create_user' => 'users#create', as: :create_user
  get '/users/:id/edit' => 'users#edit', :as => 'edit_user'

  get '/users/:id' => 'users#show', :as => 'user'
  delete 'users/:id' => 'users#destroy'
  patch '/users/:id' => 'users#update', :as => 'update_user'

  get       'enable_contact'    =>  'contacts#enable_contact'
  get       'disable_contact'   =>  'contacts#disable_contact'

  get       'enable_region'    =>  'regions#enable_region'
  get       'disable_region'   =>  'regions#disable_region'

  get       'enable_city'    =>  'cities#enable_city'
  get       'disable_city'   =>  'cities#disable_city'

  get       'enable_suburb'    =>  'suburbs#enable_suburb'
  get       'disable_suburb'   =>  'suburbs#disable_suburb'

  get       'enable_locality'    =>  'localities#enable_locality'
  get       'disable_locality'   =>  'localities#disable_locality'

  get       'enable_job_title'    =>  'job_titles#enable_job_title'
  get       'disable_job_title'   =>  'job_titles#disable_job_title'

  get       'enable_user'    =>  'users#enable_user'
  get       'disable_user'   =>  'users#disable_user'

  get       'enable_role'    =>  'roles#enable_role'
  get       'disable_role'   =>  'roles#disable_role'
  
  get  'city_cascade' => 'suburbs#city_cascade'
  get 'suburb_cascade' => 'localities#suburb_cascade'
  get 'city_update' => 'suburbs#city_update'
  get 'suburb_update' => 'localities#suburb_update'
  get 'suburb_contact_cascade' => 'contacts#suburb_contact_cascade'
  get 'locality_contact_cascade' => 'contacts#locality_contact_cascade'

end

app/models/locality.rb
class Locality < ActiveRecord::Base
   validates :suburb_id, presence: true
   validates :locality_name, presence: true

   has_many :contacts
   belongs_to :suburb

   def self.to_csv
     CSV.generate do |csv|
       csv << column_names ## Header values of CSV
       all.each do |loc|
         csv << loc.attributes.values_at(*column_names) ##Row values of CSV
       end
     end
   end
    acts_as_xlsx



      #  def self.phone_number_search(phone_number)
      #   phone_number = "%#{phone_number}%"
      #   where('phone_number LIKE ?', phone_number)
      # end

      def self.locality_name_search(locality_name)
       locality_name = "%#{locality_name}%"
       where('locality_name LIKE ?', locality_name)
     end


      def self.search_date(start = nil, ended = nil)
        if start && ended
          where(created_at: "#{start} 00:00:00".."#{ended} 23:59:59")
        else
          all
        end
      end

end

app/controllers/localities_controller.rb
class LocalitiesController < ApplicationController
  before_action :set_locality, only: [:show, :edit, :update, :destroy]

  # GET /localities
  # GET /localities.json
  def index
    @localities = Locality.all.paginate(page: params[:page], per_page: 8)


        if params[:count]
         params[:count]
       else
         params[:count] = 30
       end
       if params[:page]
         page = params[:page].to_i
       else
         page = 1
       end
       if params[:per_page].present?
         perpage = params[:per_page]
       else
         perpage = 100
       end
       @per_page = params[:per_page] || Locality.per_page || 30
       page = if params[:page]
                params[:page].to_i
              else
                1
               end
       per_page = 30
       offset = (page - 1) * per_page
       limit = page * per_page
       @array = *(offset...limit)

       if  params[:search_value] && params[:search_value].strip != ''
         if params[:search_param] == 'locality_name'
           @localities = Locality.locality_name_search(params[:search_value].strip).paginate(page: params[:page], per_page: params[:count]).order('id asc')
          elsif params[:search_param] == 'phone_number'
            logger.info "We are INSIDE THE NUMBER PARAM"
            @localities = Locality.phone_number_search(params[:search_value].strip).paginate(page: params[:page], per_page: params[:count]).order('id asc')
         elsif params[:search_param] == 'date'
           start = (params["start_date"] + " " + "0:00:00")# Time.zone.parse(params["start_date"].to_s + " " + "0:00:00").utc # params["start_date"].to_s + "0:00:00"
           ended = params["end_date"] + " " + ("23:59:59") # Time.zone.parse(params["end_date"].to_s + " " + "23:59:59").utc # params["end_date"].to_s + "23:59:59"
          @localities =Locality.search_date(start,ended).paginate(page: params[:page], per_page: params[:count]).order('id asc')

       else
          @contacts = Locality.paginate(page: params[:page], per_page: params[:count]).order('id desc')
          @search_json = []
         end
       end
       p "JSON ARRAY: #{@search_json}"




    respond_to do |format|
     format.html
     format.xlsx
     format.js
     format.csv { send_data @localities.to_csv}
   end
  end

  # GET /localities/1
  # GET /localities/1.json
  def show
  end

  def enable_locality
      locality_id=params[:id]
     if Locality.update(locality_id, :status => 1)
       redirect_to localities_path, notice: 'Locality was successfully enabled.'
     end
  end

  def disable_locality
      locality_id=params[:id]
     if Locality.update(locality_id, :status => 0)
       redirect_to localities_path, notice: 'Locality was successfully disabled.'
     end
  end

  # GET /localities/new
  def new
    @suburbs = Suburb.where('status = true' )
    @cities = City.all.order('id ASC')
    @regions = Region.all.order('id ASC')
    @locality = Locality.new
  end

  # GET /localities/1/edit
  def edit
    @suburbs = Suburb.where('status = true' )
    @cities = City.all.order('city_name ASC')
    @regions = Region.all.order('region_name ASC')

    @region_id = @locality.suburb.city.region_id 
    logger.info "region id: #{@region_id}"

    # logger.info "suburb: #{@locality.suburb.inspect}" 
    # logger.info "city:  #{@locality.suburb.city.inspect}" 
    # logger.info "region: #{@locality.suburb.city.region.inspect}"
  end

  # POST /localities
  # POST /localities.json
  def create
    @suburbs = Suburb.where('status = true' )
    @locality = Locality.new(locality_params)

    respond_to do |format|
      if @locality.save
        format.html { redirect_to @locality, notice: 'Locality was successfully created.' }
        format.json { render :show, status: :created, location: @locality }
        format.js
      else
        format.js { render :new }
        format.html { render :new }
        format.json { render json: @locality.errors, status: :unprocessable_entity }
      end
    end
  end

  def city_cascade
      region = Region.find(params[:region_id])
      # logger.info "this is the region: #{region.inspect}"

      # logger.info "cities in region: #{region.cities.inspect}"
      @cities = region.cities.map{|a| [a.city_name, a.id]}.insert(0, "Choose a city")
    end

    def suburb_cascade
      city = City.find(params[:city_id])
      # logger.info "this is the region: #{city.inspect}"

      # logger.info "cities in region: #{city.suburbs.inspect}"
      @suburbs = city.suburbs.map{|b| [b.suburb_name, b.id]}.insert(0, "Choose a suburb")
    end

    def suburb_update
      city = City.find(params[:city_id])
      @suburbs = city.suburbs.map{|b| [b.suburb_name, b.id]}.insert(1)
    end


  # PATCH/PUT /localities/1
  # PATCH/PUT /localities/1.json
  def update
    @suburbs = Suburb.where('status = true' )
    @regions = Region.all.order('id ASC')
    @cities = City.where('status = true')
    respond_to do |format|
      if @locality.update(locality_params)
        format.html { redirect_to @locality, notice: 'Locality was successfully updated.' }
        format.json { render :show, status: :ok, location: @locality }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @locality.errors, status: :unprocessable_entity }
        format.js{render :edit}
      end
    end
  end

  # DELETE /localities/1
  # DELETE /localities/1.json
  def destroy
    @locality.destroy
    respond_to do |format|
      format.html { redirect_to localities_url, notice: 'Locality was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_locality
      @locality = Locality.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def locality_params
      params.require(:locality).permit(:suburb_id, :locality_name, :status)
    end
end

app/helpers/localities_helper.rb
module LocalitiesHelper
end

app/views/localities/_edit.html.erb
<div class="row">
     <div class="col-md-4 xs-3"></div>

     <div class="col-md-4 xs-6" id="form" style="border-radius: 3%">
          <h3>Edit Locality</h3>
        <%= render 'form' %>
          <!-- <%= link_to 'Show', @contact, style: 'margin-left: 50%; margin-top: -5%' %> -->
     </div>

     <div class="col-md-4 xs-3"></div>
</div>
<br><br>

app/views/localities/_form.html.erb
<%= simple_form_for(@locality, :remote=>true) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
<%if @locality.persisted? %>
<%= f.input :suburb_id, label: 'Region', collection: @regions, label_method: :region_name, value_method: :id, input_html: {id: "id_regions" }  %>
<%else %>
<%= f.input :suburb_id, label: 'Region', collection: @regions, label_method: :region_name, value_method: :id, input_html: {id: "id_regions" }  %>


<%end %>
   <%= f.input :suburb_id, label: "City", collection: [], label_method: :city_name, value_method: :id, input_html:{id: "id_cities"}  %>

    <%= f.input :suburb_id, collection: [], label_method: :suburb_name, value_method: :id, input_html:{id: "id_suburbs"}  %>

    <%= f.input :locality_name %>

    <%= f.input :status, :as=> :hidden, input_html: {value: 1 } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn-success', remote: true %>
    <%= link_to ' Go Back', localities_path, class: 'pull-right btn btn-info fa fa-angle-double-left', :remote=>true %>
  </div>
  <br>
<% end %>

<script type="text/javascript">
    $(document).ready(function() {
        console.log('works');
        //empty it
//        $('#id_cities').empty();
        //before ajax call

        //when region field if loaded
        //  $('#id_regions').ready(function() {
        //    // console.log('works on change for keep');
        //     $.ajax({
        //         url: '<%= city_update_path %>',
        //         data: {
        //             region_id : $('#id_regions').val()
        //         },
        //         dataType: "script"
        //     });
        // });

        //when city field is loaded
        // $('#id_cities').ready(function() {
        //    console.log('City loaded');


        // setTimeout(function(){
        //     console.log('ready');
        //   $.ajax({
        //                 url: '<%= suburb_update_path %>',
        //                 data: {
        //                     city_id : $('#id_cities').val()
        //                 },
        //                 dataType: "script"
        //             });

        //         }, 2000);

        //     setTimeout(function(){
        //         $("#id_suburbs option").each(function(){
        //             console.log("current"+$(this).val());
        //             console.log(" suburb id: <%= @locality.suburb_id %>");

        //           if ($(this).val() == "<%= @locality.suburb_id %>"){
        //             console.log('selected attr added');
        //             $(this).attr("selected","selected");
        //             }

        //             });

        //     }, 2000);

        // });



        $('#id_regions').change(function() {
           // console.log('works on change');
            $.ajax({
                url: '<%= city_cascade_path %>',
                data: {
                    region_id : $('#id_regions').val()
                },
                dataType: "script"
            });
        });


     });

    </script>

    <script type="text/javascript">
    $(document).ready(function() {
        console.log('works');
        //empty it
//        $('#id_cities').empty();
        //before ajax call

        $('#id_cities').change(function() {
           console.log('works on change');
            $.ajax({
                url: '<%= suburb_cascade_path %>',
                data: {
                    city_id : $('#id_cities').val()
                },
                dataType: "script"
            });
        });
    });

    </script>

app/views/localities/_index.html.erb
<!-- <p id="notice"><%= notice %></p> -->


<h3>Listing Localities</h3>

<div class="col-md-2"></div>

<div class="col-md-8">
    <div class="table-responsive" style="border: none">

    <table class="table table-striped table-bordered table-condensed">

      <thead>
        <tr style="background: #F5FFFA;">
            <p style = 'text-align: center; font-family: tahoma; font-size: 15px;'><b>Download:</b> <%= link_to "csv", localities_path(format: "csv") %> | <%= link_to "excel", localities_path(format: "xlsx") %> </p>
        <% if current_user.present? && current_user.role_id == 1 %>
          <%= link_to 'New Locality', new_locality_path, class: 'btn btn-default pull-right', style: 'position: fixed', :remote=> true %>
        <% end %>


          <%=form_tag localities_path, method: :get, input_html:{display:"block"} do %>

              <div class="pull-right"><input id="locality_name" type="radio" name="search_param" value="locality_name" style="width: auto;" /> Filter by Locality  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>

              <!-- <div class="pull-right"><input id="phone_number" type="radio" name="search_param" value="phone_number" style="width: auto; " /> Filter by phone number &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div> -->


              <input type="submit" id="search-field2" class=" hidden btn btn-primary pull-right" value="Search" style="margin-right: -10px">

              <div class="form-inline" style="margin-left: 10px">
                  <input id="search-field" class="form-control hidden pull-right"  name="search_value" />
              </div>

         <% end %>

          <br><br>

          <th style="width: 5%">S/N</th>
          <th>Suburb</th>
          <th>Locality name</th>

        <% if current_user.present? && current_user.role_id == 1 %>
          <th colspan="3" style="width: 15%">Options</th>

        <% else %>
           <th style="width: 10%">Options</th>
        <% end %>

        </tr>
      </thead>

      <tbody>
        <% @localities.each do |locality| %>
          <tr>
            <td><%= locality.id %></td>
            <td><%= locality.suburb.suburb_name if locality.suburb %></td>
            <td><%= locality.locality_name %></td>
            <td><%= link_to ' Show', locality, class: 'btn btn-info fa fa-eye', :remote=>true %></td>

          <% if current_user.present? && current_user.role_id == 1 %>
            <td><%= link_to ' Edit', edit_locality_path(locality), class: 'btn btn-default fa fa-edit' %></td>
            <!-- <td><%= link_to ' Delete', locality, method: :delete, class: 'btn btn-danger fa fa-remove', data: { confirm: 'Are you sure?' } %></td> -->

            <td>
              <% if locality.status == false %>
                  <%= link_to 'Enable', enable_locality_path(:id => locality.id), :class => 'btn btn-success'%>
                  <% else locality.status == true %>
                  <%= link_to 'Disable', disable_locality_path(:id => locality.id), :class => 'btn btn-danger',data: {confirm: 'Are you sure?'}%>
              <% end %>
            </td>

         <% end %>

          </tr>
        <% end %>
      </tbody>

    </table>

    <%= will_paginate @localities, renderer: BootstrapPagination::Rails, previous_label: 'Older', next_lable: 'Newer', class: 'pagination-sm'  %>

    </div>
</div>

<div class="col-md-2"></div>
<br>

<script>
    $(document).ready(function() {
        $(".radio_div div input").click(function() {
            $("#date_div").addClass("hidden");
            $("#search-field").removeClass("hidden");
            $("#narrative_div").addClass("hidden");
            //$("#date_div").fadeIn('slow');
        });
        $("#locality_name").click(function() {
            if ($("#locality_name").is(":checked")) {
                $("#search-field").attr("placeholder", "Locality");
                $("#search-field2").removeClass("hidden")
                $("#search-field").removeClass("hidden");
            }
        });
        ////////////////////////////////////////////////////////////////////////////
        $("#phone_number").click(function() {
            if ($("#phone_number").is(":checked")) {
                $("#search-field").attr("placeholder", "Mobile number");
                $("#date_div").addClass("hidden");
                $("#search-field").removeClass("hidden");
                $("#search-field2").removeClass("hidden")
            }
        });
        $("#recipient_number").click(function() {
            if ($("#recipient_number").is(":checked")) {
                $("#search-field").attr("placeholder", "Recipient Number");
                $("#date_div").addClass("hidden");
                $("#search-field").removeClass("hidden");
            }
        });
        //////////////////////////clicking on filter by date
        $("#date").click(function() {
            //if ($("#date").is(":checked")){
            $("#date_div").removeClass("hidden");
            $("#search-field").addClass("hidden");
            $("#date-field").removeClass("hidden");
            $("#date-field2").removeClass("hidden");
            $("#search-field2").removeClass("hidden")
            //$("#date_div").fadeIn('slow');
            //}
        });
        $("#date-field").click(function() {
            //if ($("#date").is(":checked")){
            $("#date_div").removeClass("hidden");
            $("#search-field").addClass("hidden");
            $("#date-field").removeClass("hidden");
            $("#date-field2").removeClass("hidden");
            $("#search-field2").removeClass("hidden")
            //$("#date_div").fadeIn('slow');
            //}
        });
        $("#date-field2").click(function() {
            //if ($("#date").is(":checked")){
            $("#date_div").removeClass("hidden");
            $("#search-field").addClass("hidden");
            $("#date-field").removeClass("hidden");
            $("#date-field2").removeClass("hidden");
            $("#search-field2").removeClass("hidden")
            //$("#date_div").fadeIn('slow');
            //}
        });
        ///////////////////////////////////////////////////
        // $.fn.datepicker.noConflict = function() {
        //     $.fn.datepicker = old;
        //     return this;
        // };
        // ////////////////////////////////////////////////////
        // $(function() {
        //     $('#date-field').datepicker({
        //         dateFormat : 'yy-mm-dd'
        //     });
        // });
        // //////////////////////////////////////////////////////
        // $(function() {
        //     $('#date-field2').datepicker({
        //         dateFormat : 'yy-mm-dd'
        //     });
        // });
        $('#csv').click(function() {
            console.log('works!');
            $('#csv_perpage').val($('#record').val());
            $('#csv_page').val($('li.active span').html());
            $('#csv_submit').click();
            console.log('works!');
        });
        /////////////////////////////////////////////////////////////
        $('#excel').click(function() {
            $('#excel_perpage').val($('#record').val());
            $('#excel_page').val($('li.active span').html());
            $('#excel_submit').click();
        });
    });
</script>

app/views/localities/_new.html.erb
<div class="row">
     <div class="col-md-4 xs-3"></div>

     <div class="col-md-4 xs-6" id="form" style="border-radius: 3%; ">
          <h3>New Locality</h3>
        <%= render 'form' %>
          <!-- <%= link_to 'Show', @contact, style: 'margin-left: 50%; margin-top: -5%' %> -->
     </div>

     <div class="col-md-4 xs-3"></div>
</div>
<br><br>

app/views/localities/_show.html.erb
<div class="row">
   <div class="col-md-3 xs-3"></div>

   <div class="col-md-6 xs-12" id="content">
     <p id="notice"><%= notice %></p>

     <table class="table table-striped">
     <h3>Listing Locality</h3>
	     <thead>
		    <tr>
		      <th>Suburb</th>
		      <th>Locality Name</th>
		    </tr>
		 </thead>

		 <tbody>
		    <td><%= @locality.suburb.suburb_name if @locality.suburb %></td>
		    <td><%= @locality.locality_name %></td>
		 </tbody>

    </table>

  <% if current_user.present? && current_user.role_id == 1 %>
    <%= link_to ' Edit Suburb', edit_locality_path(@locality), class: 'btn btn-success', remote: true %>
  <% end %>
  
    <%= link_to ' Go Back', localities_path, class: 'btn btn-info  pull-right fa fa-angle-double-left', :remote=>true %>

   </div>

   <div class="col-md-3 xs-3"></div>
</div>

<!-- <p id="notice"><%= notice %></p>

<p>
  <strong>Suburb:</strong>
  <%= @locality.suburb_id %>
</p>

<p>
  <strong>Locality name:</strong>
  <%= @locality.locality_name %>
</p>

<%= link_to 'Edit', edit_locality_path(@locality) %> |
<%= link_to 'Back', localities_path %> -->

app/views/localities/city_cascade.js.erb
$('#id_cities').html("<%= escape_javascript(options_for_select(@cities)) %>");

app/views/localities/city_update.js.erb
$('#id_cities').html("<%= escape_javascript(options_for_select(@cities)) %>");

app/views/localities/create.js.erb
$("#localities").html("<%= escape_javascript(render(:partial =>"show")) %>");

app/views/localities/edit.js.erb
$("#localities").html("<%= escape_javascript(render(:partial =>"edit")) %>");

app/views/localities/index.js.erb
$("#localities").html("<%= escape_javascript(render(:partial =>"index")) %>");

app/views/localities/show.js.erb
$("#localities").html("<%= escape_javascript(render(:partial =>"show")) %>");

app/views/localities/suburb_cascade.js.erb
$('#id_suburbs').html("<%= escape_javascript(options_for_select(@suburbs)) %>");

app/views/localities/update.js.erb
$("#localities").html("<%= escape_javascript(render(:partial =>"show")) %>");