config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :contacts
  get 'home/index'
  root to: 'home#index'

  resources :roles
  resources :job_titles
  resources :localities
  resources :suburbs
  resources :cities
  resources :regions
  resources :contats

  devise_scope :user do
    get '/users/sign_up' => 'users#sign_in'
  end

   get '/users' => 'users#index'

  get '/users/new' => 'users#new', :as => 'new_user'
  post 'create_user' => 'users#create', as: :create_user
  get '/users/:id/edit' => 'users#edit', :as => 'edit_user'

  get '/users/:id' => 'users#show', :as => 'user'
  delete 'users/:id' => 'users#destroy'
  patch '/users/:id' => 'users#update', :as => 'update_user'

  get       'enable_contact'    =>  'contacts#enable_contact'
  get       'disable_contact'   =>  'contacts#disable_contact'

  get       'enable_region'    =>  'regions#enable_region'
  get       'disable_region'   =>  'regions#disable_region'

  get       'enable_city'    =>  'cities#enable_city'
  get       'disable_city'   =>  'cities#disable_city'

  get       'enable_suburb'    =>  'suburbs#enable_suburb'
  get       'disable_suburb'   =>  'suburbs#disable_suburb'

  get       'enable_locality'    =>  'localities#enable_locality'
  get       'disable_locality'   =>  'localities#disable_locality'

  get       'enable_job_title'    =>  'job_titles#enable_job_title'
  get       'disable_job_title'   =>  'job_titles#disable_job_title'

  get       'enable_user'    =>  'users#enable_user'
  get       'disable_user'   =>  'users#disable_user'

  get       'enable_role'    =>  'roles#enable_role'
  get       'disable_role'   =>  'roles#disable_role'
  
  get  'city_cascade' => 'suburbs#city_cascade'
  get 'suburb_cascade' => 'localities#suburb_cascade'
  get 'city_update' => 'suburbs#city_update'
  get 'suburb_update' => 'localities#suburb_update'
  get 'suburb_contact_cascade' => 'contacts#suburb_contact_cascade'
  get 'locality_contact_cascade' => 'contacts#locality_contact_cascade'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

          # validates :username, presence: true
          # validates :email, email: true
          # validates :password, presence: true
          # validates :password_confirmation, presence: true
          # validates :role_id, presence: true

         belongs_to :role, class_name: "Role", foreign_key: :role_id

         def active_for_authentication?

            super && status?
         end

         def self.to_csv
           CSV.generate do |csv|
             csv << column_names ## Header values of CSV
             all.each do |cont|
               csv << cont.attributes.values_at(*column_names) ##Row values of CSV
             end
           end
         end
          acts_as_xlsx

            #
            #  def self.phone_number_search(phone_number)
            #   phone_number = "%#{phone_number}%"
            #   where('phone_number LIKE ?', phone_number)
            # end

            def self.username_search(username)
             username = "%#{username}%"
             where('username LIKE ?', username)
           end


            def self.search_date(start = nil, ended = nil)
              if start && ended
                where(created_at: "#{start} 00:00:00".."#{ended} 23:59:59")
              else
                all
              end
            end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all.paginate(page: params[:page], per_page: 8)

        if params[:count]
         params[:count]
       else
         params[:count] = 30
       end
       if params[:page]
         page = params[:page].to_i
       else
         page = 1
       end
       if params[:per_page].present?
         perpage = params[:per_page]
       else
         perpage = 100
       end
       @per_page = params[:per_page] || User.per_page || 30
       page = if params[:page]
                params[:page].to_i
              else
                1
               end
       per_page = 30
       offset = (page - 1) * per_page
       limit = page * per_page
       @array = *(offset...limit)

       if  params[:search_value] && params[:search_value].strip != ''
         if params[:search_param] == 'username'
           @users = User.username_search(params[:search_value].strip).paginate(page: params[:page], per_page: params[:count]).order('id asc')
          elsif params[:search_param] == 'phone_number'
            logger.info "We are INSIDE THE NUMBER PARAM"
            @users = User.phone_number_search(params[:search_value].strip).paginate(page: params[:page], per_page: params[:count]).order('id asc')
         elsif params[:search_param] == 'date'
           start = (params["start_date"] + " " + "0:00:00")# Time.zone.parse(params["start_date"].to_s + " " + "0:00:00").utc # params["start_date"].to_s + "0:00:00"
           ended = params["end_date"] + " " + ("23:59:59") # Time.zone.parse(params["end_date"].to_s + " " + "23:59:59").utc # params["end_date"].to_s + "23:59:59"
           @users =User.search_date(start,ended).paginate(page: params[:page], per_page: params[:count]).order('id asc')

       else
          @users = User.paginate(page: params[:page], per_page: params[:count]).order('id desc')
          @search_json = []
         end
       end
       p "JSON ARRAY: #{@search_json}"



    respond_to do |format|
     format.html
     format.xlsx
     format.csv { send_data @users.to_csv}
   end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

# enable user
  def enable_user
      user_id=params[:id]
     if User.update(user_id, :status => 1)
       redirect_to users_path, notice: 'User was successfully enabled.'
     end
  end

# disable user
  def disable_user
      user_id=params[:id]
     if User.update(user_id, :status => 0)
       redirect_to users_path, notice: 'User was successfully disabled.'
     end
  end

  # GET /users/new
  def new
    @roles = Role.where('status = true' )
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @roles = Role.where('status = true' )
  end

  # POST /users
  # POST /users.json
  def create
    @roles = Role.where('status = true' )
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @roles = Role.where('status = true' )
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @roles = Role.where('status = true' )
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation,:role_id, :status)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_form.html.erb
<%= simple_form_for(@user, url: update_user_path) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

   <%= f.input :username, required: true %>

   <%= f.input :email, required: true %>

  <% if current_user.present? && current_user.role_id == 1 %>
      <%= f.input :role_id, collection: @roles, label_method: :role_name, value_method: :id %>

  <% else %>
      <%= f.input :role_id, collection: @roles, label_method: :role_name, value_method: :id, disabled: true %>
  <% end %>


  </div>

  <%= f.submit "Update User", class: "btn btn-success" %>

    <% if current_user.present? && current_user.role_id == 1 %>
       <%= link_to ' Go Back', users_path, class: 'pull-right btn btn-info fa fa-angle-double-left' %>

    <% else %>
      <%= link_to ' Go Back', :back, class: 'pull-right btn btn-info fa fa-angle-double-left' %>
    <% end %>
  <br><br>
<% end %>

app/views/users/_form.html.erb
<%= simple_form_for(@user, url: create_user_path) do |f| %>
  <%= f.error_notification %>

<div class="form-inputs">

   <%= f.input :username, required: true %>

  <%= f.input :email, required: true, email: true %>

   <%= f.input :password, required: true %>


   <%= f.input :password_confirmation, required: true %>
  <%= f.input :role_id, collection: @roles, label_method: :role_name, value_method: :id, required: true %>
    <%= f.input :status, :as=> :hidden, input_html: {value: 1 } %>
</div>

  <div class="form-actions">
    <%= f.submit "Create User", class: "btn btn-success" %>
    <%= link_to ' Go Back', users_path, class: 'pull-right btn btn-info fa fa-angle-double-left' %>
</div>
<br>
<% end %>

app/views/users/edit.html.erb
<div class="row">
     <div class="col-md-4 xs-3"></div>

     <div class="col-md-4 xs-6" id="form" style="border-radius: 3%">
          <h3>Edit User</h3>
          <%= render 'edit_form' %>

          <!-- <%= link_to 'Show', @contact, style: 'margin-left: 50%; margin-top: -5%' %> -->
     </div>

     <div class="col-md-4 xs-3"></div>
</div>
<br><br>

<!-- <%= link_to 'Show', @user %> | -->

app/views/users/index.html.erb
<h3>Listing Users</h3>

<div class="table-responsive" style="border: none">
    <table class="table table-striped table-condensed table-bordered">
      <thead>
        <tr style="background: #F5FFFA;">
            <p style = 'text-align: center; font-family: tahoma; font-size: 15px;'><b>Download:</b> <%= link_to "csv", users_path(format: "csv") %> | <%= link_to "excel", users_path(format: "xlsx") %> </p>
           <%= link_to 'New User', new_user_path, class: 'btn btn-default pull-right', style: 'position: fixed' %>

           <%=form_tag users_path, method: :get, input_html:{display:"block"} do %>

           <div class="pull-right"><input id="username" type="radio" name="search_param" value="username" style="width: auto;" /> Filter by username &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>

            <!-- <div class="pull-right"><input id="phone_number" type="radio" name="search_param" value="phone_number" style="width: auto; " /> Filter by phone number &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div> -->


           <input type="submit" id="search-field2" class=" hidden btn btn-primary pull-right" value="Search" style="margin-right: -10px">

           <div class="form-inline" style="margin-left: 10px">
              <input id="search-field" class="form-control hidden pull-right"  name="search_value" />
           </div>

           <% end %>

           <br><br>
          <th>S/N</th>
          <th>Username</th>
          <th>Email</th>
          <th>Role</th>
          <th colspan="3" style="width: 15%">Options</th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= user.username %></td>
            <td><%= user.email %></td>
            <td><%= user.role.role_name if user.role %></td>

            <td><%= link_to ' Show', user, class: 'btn btn-info fa fa-eye' %></td>
            <td><%= link_to ' Edit', edit_user_path(user), class: 'btn btn-default fa fa-edit' %></td>
            <!-- <td><%= link_to ' Delete', user, method: :delete, class: 'btn btn-danger fa fa-remove', data: { confirm: 'Are you sure?' } %></td> -->

            <td>
              <% if user.status == false %>
                  <%= link_to 'Enable', enable_user_path(:id => user.id), :class => 'btn btn-success'%>
                  <% else user.status == true %>
                  <%= link_to 'Disable', disable_user_path(:id => user.id), :class => 'btn btn-danger',data: {confirm: 'Are you sure?'}%>
              <% end %>
            </td>

          </tr>
        <% end %>
      </tbody>
    </table>

    <%= will_paginate @users, renderer: BootstrapPagination::Rails, previous_label: 'Older', next_lable: 'Newer', class: 'pagination-sm'  %>

</div>

<br>

<script>
    $(document).ready(function() {
        $(".radio_div div input").click(function() {
            $("#date_div").addClass("hidden");
            $("#search-field").removeClass("hidden");
            $("#narrative_div").addClass("hidden");
            //$("#date_div").fadeIn('slow');
        });
        $("#username").click(function() {
            if ($("#username").is(":checked")) {
                $("#search-field").attr("placeholder", "Username");
                $("#search-field2").removeClass("hidden")
                $("#search-field").removeClass("hidden");
            }
        });
        ////////////////////////////////////////////////////////////////////////////
        $("#phone_number").click(function() {
            if ($("#phone_number").is(":checked")) {
                $("#search-field").attr("placeholder", "Mobile number");
                $("#date_div").addClass("hidden");
                $("#search-field").removeClass("hidden");
                $("#search-field2").removeClass("hidden")
            }
        });
        $("#recipient_number").click(function() {
            if ($("#recipient_number").is(":checked")) {
                $("#search-field").attr("placeholder", "Recipient Number");
                $("#date_div").addClass("hidden");
                $("#search-field").removeClass("hidden");
            }
        });
        //////////////////////////clicking on filter by date
        $("#date").click(function() {
            //if ($("#date").is(":checked")){
            $("#date_div").removeClass("hidden");
            $("#search-field").addClass("hidden");
            $("#date-field").removeClass("hidden");
            $("#date-field2").removeClass("hidden");
            $("#search-field2").removeClass("hidden")
            //$("#date_div").fadeIn('slow');
            //}
        });
        $("#date-field").click(function() {
            //if ($("#date").is(":checked")){
            $("#date_div").removeClass("hidden");
            $("#search-field").addClass("hidden");
            $("#date-field").removeClass("hidden");
            $("#date-field2").removeClass("hidden");
            $("#search-field2").removeClass("hidden")
            //$("#date_div").fadeIn('slow');
            //}
        });
        $("#date-field2").click(function() {
            //if ($("#date").is(":checked")){
            $("#date_div").removeClass("hidden");
            $("#search-field").addClass("hidden");
            $("#date-field").removeClass("hidden");
            $("#date-field2").removeClass("hidden");
            $("#search-field2").removeClass("hidden")
            //$("#date_div").fadeIn('slow');
            //}
        });
        ///////////////////////////////////////////////////
        $.fn.datepicker.noConflict = function() {
            $.fn.datepicker = old;
            return this;
        };
        ////////////////////////////////////////////////////
        $(function() {
            $('#date-field').datepicker({
                dateFormat : 'yy-mm-dd'
            });
        });
        //////////////////////////////////////////////////////
        $(function() {
            $('#date-field2').datepicker({
                dateFormat : 'yy-mm-dd'
            });
        });
        $('#csv').click(function() {
            console.log('works!');
            $('#csv_perpage').val($('#record').val());
            $('#csv_page').val($('li.active span').html());
            $('#csv_submit').click();
            console.log('works!');
        });
        /////////////////////////////////////////////////////////////
        $('#excel').click(function() {
            $('#excel_perpage').val($('#record').val());
            $('#excel_page').val($('li.active span').html());
            $('#excel_submit').click();
        });
    });
</script>

app/views/users/new.html.erb
<div class="row">
     <div class="col-md-4 xs-3"></div>

     <div class="col-md-4 xs-6" id="form" style="border-radius: 3%">
          <h3>New User</h3>
        <%= render 'form' %>
          <!-- <%= link_to 'Show', @contact, style: 'margin-left: 50%; margin-top: -5%' %> -->
     </div>

     <div class="col-md-4 xs-3"></div>
</div>

app/views/users/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<div class="col-md-3 xs-12"></div>

   <div class="col-md-6 xs-12" id="content">
       <table class="table table-striped table-condensed table-bordered">
         <h3>User Details</h3>
    	     <thead>
    		    <tr>
    		      <th>Username</th>
    		      <th>Email</th>
              <th>User Role</th>
    		    </tr>
    		 </thead>

    		 <tbody>
    		    <td><%= @user.username %></td>
    		    <td><%= @user.email %></td>
            <td><%= @user.role.role_name if @user.role %></td>
    		 </tbody>

        </table>

      <% if current_user.present? && current_user.role_id == 1 %>
        <%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-success' %>
        <%= link_to ' Go Back', :back, class: 'btn btn-info pull-right fa fa-angle-double-left' %>

      <% else %>
          <%= link_to ' Go Back', edit_user_path(@user), class: 'btn btn-info pull-right fa fa-angle-double-left' %>
      <% end %>

    </div>

<div class="col-md-3 xs-12"></div>