config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :contacts
  get 'home/index'
  root to: 'home#index'

  resources :roles
  resources :job_titles
  resources :localities
  resources :suburbs
  resources :cities
  resources :regions
  resources :contats

  devise_scope :user do
    get '/users/sign_up' => 'users#sign_in'
  end

   get '/users' => 'users#index'

  get '/users/new' => 'users#new', :as => 'new_user'
  post 'create_user' => 'users#create', as: :create_user
  get '/users/:id/edit' => 'users#edit', :as => 'edit_user'

  get '/users/:id' => 'users#show', :as => 'user'
  delete 'users/:id' => 'users#destroy'
  patch '/users/:id' => 'users#update', :as => 'update_user'

  get       'enable_contact'    =>  'contacts#enable_contact'
  get       'disable_contact'   =>  'contacts#disable_contact'

  get       'enable_region'    =>  'regions#enable_region'
  get       'disable_region'   =>  'regions#disable_region'

  get       'enable_city'    =>  'cities#enable_city'
  get       'disable_city'   =>  'cities#disable_city'

  get       'enable_suburb'    =>  'suburbs#enable_suburb'
  get       'disable_suburb'   =>  'suburbs#disable_suburb'

  get       'enable_locality'    =>  'localities#enable_locality'
  get       'disable_locality'   =>  'localities#disable_locality'

  get       'enable_job_title'    =>  'job_titles#enable_job_title'
  get       'disable_job_title'   =>  'job_titles#disable_job_title'

  get       'enable_user'    =>  'users#enable_user'
  get       'disable_user'   =>  'users#disable_user'

  get       'enable_role'    =>  'roles#enable_role'
  get       'disable_role'   =>  'roles#disable_role'
  
  get  'city_cascade' => 'suburbs#city_cascade'
  get 'suburb_cascade' => 'localities#suburb_cascade'
  get 'city_update' => 'suburbs#city_update'
  get 'suburb_update' => 'localities#suburb_update'
  get 'suburb_contact_cascade' => 'contacts#suburb_contact_cascade'
  get 'locality_contact_cascade' => 'contacts#locality_contact_cascade'

end

app/models/job_title.rb
class JobTitle < ActiveRecord::Base
  validates :job_title_name, presence: true

	has_one :contacts

  def self.to_csv
    CSV.generate do |csv|
      csv << column_names ## Header values of CSV
      all.each do |cont|
        csv << cont.attributes.values_at(*column_names) ##Row values of CSV
      end
    end
  end
   acts_as_xlsx


    #   def self.phone_number_search(phone_number)
    #    phone_number = "%#{phone_number}%"
    #    where('phone_number LIKE ?', phone_number)
    #  end

     def self.job_title_name_search(job_title_name)
      job_title_name = "%#{job_title_name}%"
      where('job_title_name LIKE ?', job_title_name)
    end


     def self.search_date(start = nil, ended = nil)
       if start && ended
         where(created_at: "#{start} 00:00:00".."#{ended} 23:59:59")
       else
         all
       end
     end

end

app/controllers/job_titles_controller.rb
class JobTitlesController < ApplicationController
  before_action :set_job_title, only: [:show, :edit, :update, :destroy]

  # GET /job_titles
  # GET /job_titles.json
  def index
    @job_titles = JobTitle.all.paginate(page: params[:page], per_page: 6)


        if params[:count]
         params[:count]
       else
         params[:count] = 30
       end
       if params[:page]
         page = params[:page].to_i
       else
         page = 1
       end
       if params[:per_page].present?
         perpage = params[:per_page]
       else
         perpage = 100
       end
       @per_page = params[:per_page] || JobTitle.per_page || 30
       page = if params[:page]
                params[:page].to_i
              else
                1
               end
       per_page = 30
       offset = (page - 1) * per_page
       limit = page * per_page
       @array = *(offset...limit)

       if  params[:search_value] && params[:search_value].strip != ''
         if params[:search_param] == 'job_title_name'
           @job_titles = JobTitle.job_title_name_search(params[:search_value].strip).paginate(page: params[:page], per_page: params[:count]).order('id asc')
          elsif params[:search_param] == 'phone_number'
            logger.info "We are INSIDE THE NUMBER PARAM"
            @job_titles = JobTitle.phone_number_search(params[:search_value].strip).paginate(page: params[:page], per_page: params[:count]).order('id asc')
         elsif params[:search_param] == 'date'
           start = (params["start_date"] + " " + "0:00:00")# Time.zone.parse(params["start_date"].to_s + " " + "0:00:00").utc # params["start_date"].to_s + "0:00:00"
           ended = params["end_date"] + " " + ("23:59:59") # Time.zone.parse(params["end_date"].to_s + " " + "23:59:59").utc # params["end_date"].to_s + "23:59:59"
           @job_titles =JobTitle.search_date(start,ended).paginate(page: params[:page], per_page: params[:count]).order('id asc')

       else
          @job_titles = JobTitle.paginate(page: params[:page], per_page: params[:count]).order('id desc')
          @search_json = []
         end
       end
       p "JSON ARRAY: #{@search_json}"



    respond_to do |format|
     format.html
     format.xlsx
     format.csv { send_data @job_titles.to_csv}
   end
  end

  # GET /job_titles/1
  # GET /job_titles/1.json
  def show
  end

  def enable_job_title
      job_title_id=params[:id]
     if JobTitle.update(job_title_id, :status => 1)
       redirect_to job_titles_path, notice: 'Job title was successfully enabled.'
     end
  end

  def disable_job_title
      job_title_id=params[:id]
     if JobTitle.update(job_title_id, :status => 0)
       redirect_to job_titles_path, notice: 'Job title was successfully disabled.'
     end
  end

  # GET /job_titles/new
  def new
    @job_title = JobTitle.new
  end

  # GET /job_titles/1/edit
  def edit
  end

  # POST /job_titles
  # POST /job_titles.json
  def create
    @job_title = JobTitle.new(job_title_params)

    respond_to do |format|
      if @job_title.save
        format.html { redirect_to @job_title, notice: 'Job title was successfully created.' }
        format.json { render :show, status: :created, location: @job_title }
      else
        format.html { render :new }
        format.json { render json: @job_title.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_titles/1
  # PATCH/PUT /job_titles/1.json
  def update
    respond_to do |format|
      if @job_title.update(job_title_params)
        format.html { redirect_to @job_title, notice: 'Job title was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_title }
      else
        format.html { render :edit }
        format.json { render json: @job_title.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_titles/1
  # DELETE /job_titles/1.json
  def destroy
    @job_title.destroy
    respond_to do |format|
      format.html { redirect_to job_titles_url, notice: 'Job title was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_title
      @job_title = JobTitle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_title_params
      params.require(:job_title).permit(:job_title_name, :status)
    end
end

app/helpers/job_titles_helper.rb
module JobTitlesHelper
end

app/views/job_titles/_form.html.erb
<%= simple_form_for(@job_title) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :job_title_name %>
      <%= f.input :status, :as=> :hidden, input_html: {value: 1 } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn-success' %>
    <%= link_to ' Go Back', job_titles_path, class: 'pull-right btn btn-info fa fa-angle-double-left' %>
  </div>
<% end %>

app/views/job_titles/edit.html.erb
<div class="row">
     <div class="col-md-4 xs-3"></div>

     <div class="col-md-4 xs-6" id="form" style="border-radius: 3%">
          <h3>Edit Job Title</h3>
        <%= render 'form' %>
          <!-- <%= link_to 'Show', @contact, style: 'margin-left: 50%; margin-top: -5%' %> -->
     </div>

     <div class="col-md-4 xs-3"></div>
</div>
<br><br>

<!-- <h1>Editing Job Title</h1>

<%= render 'form' %>

<%= link_to 'Show', @job_title %> |
<%= link_to 'Back', job_titles_path %> -->

app/views/job_titles/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h3>Listing Job Titles</h3>

<div class="col-md-3"></div>

<div class="col-md-6">
      <div class="table-responsive" style="border: none">

          <table class="table table-striped table-condensed table-bordered">
            <thead>
              <tr style="background: #F5FFFA;">
                  <p style = 'text-align: center; font-family: tahoma; font-size: 15px;'><b>Download:</b> <%= link_to "csv", job_titles_path(format: "csv") %> | <%= link_to "excel", job_titles_path(format: "xlsx") %> </p>
              <% if current_user.present? && current_user.role_id == 1 %>
                  <%= link_to 'New Job title', new_job_title_path, class: 'btn btn-default pull-right', style: 'position: fixed' %>
              <% end %>


              <%=form_tag job_titles_path, method: :get, input_html:{display:"block"} do %>

                <div class="pull-right"><input id="job_title_name" type="radio" name="search_param" value="job_title_name" style="width: auto;" /> Filter by job title &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>

                <!-- <div class="pull-right"><input id="phone_number" type="radio" name="search_param" value="phone_number" style="width: auto; " /> Filter by phone number &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div> -->


                <input type="submit" id="search-field2" class=" hidden btn btn-primary pull-right" value="Search" style="margin-right: -10px">

                <div class="form-inline" style="margin-left: 10px">
                     <input id="search-field" class="form-control hidden pull-right"  name="search_value" />
                </div>

            <% end %>


                  <br><br>
                <th style="width: 5%">S/N</th>
                <th>Job title name</th>
              <% if current_user.present? && current_user.role_id == 1 %>
                <th colspan="3" style="width: 15%">Options</th>

              <% else %>
                <th style="width: 10%">Options</th>
              <% end %>

              </tr>
            </thead>

            <tbody>
              <% @job_titles.each do |job_title| %>
                <tr>
                  <td><%= job_title.id %></td>
                  <td><%= job_title.job_title_name %></td>
                  <td><%= link_to ' Show', job_title, class: 'btn btn-info fa fa-eye' %></td>

                <% if current_user.present? && current_user.role_id == 1 %>
                  <td><%= link_to ' Edit', edit_job_title_path(job_title), class: 'btn btn-default fa fa-edit' %></td>
                  <!-- <td><%= link_to ' Delete', job_title, method: :delete, class: 'btn btn-danger fa fa-remove', data: { confirm: 'Are you sure?' } %></td> -->

                  <td>
                    <% if job_title.status == false %>
                        <%= link_to 'Enable', enable_job_title_path(:id => job_title.id), :class => 'btn btn-success'%>
                        <% else job_title.status == true %>
                        <%= link_to 'Disable', disable_job_title_path(:id => job_title.id), :class => 'btn btn-danger',data: {confirm: 'Are you sure?'}%>
                    <% end %>
                  </td>

               <% end %>

                </tr>
              <% end %>
            </tbody>
          </table>

          <%= will_paginate @job_titles, renderer: BootstrapPagination::Rails, previous_label: 'Older', next_lable: 'Newer', class: 'pagination-sm'  %>

      </div>
</div>
<div class="col-md-3"></div>
<br>

<script>
    $(document).ready(function() {
        $(".radio_div div input").click(function() {
            $("#date_div").addClass("hidden");
            $("#search-field").removeClass("hidden");
            $("#narrative_div").addClass("hidden");
            //$("#date_div").fadeIn('slow');
        });
        $("#job_title_name").click(function() {
            if ($("#job_title_name").is(":checked")) {
                $("#search-field").attr("placeholder", "Job Title");
                $("#search-field2").removeClass("hidden")
                $("#search-field").removeClass("hidden");
            }
        });
        ////////////////////////////////////////////////////////////////////////////
        $("#phone_number").click(function() {
            if ($("#phone_number").is(":checked")) {
                $("#search-field").attr("placeholder", "Mobile number");
                $("#date_div").addClass("hidden");
                $("#search-field").removeClass("hidden");
                $("#search-field2").removeClass("hidden")
            }
        });
        $("#recipient_number").click(function() {
            if ($("#recipient_number").is(":checked")) {
                $("#search-field").attr("placeholder", "Recipient Number");
                $("#date_div").addClass("hidden");
                $("#search-field").removeClass("hidden");
            }
        });
        //////////////////////////clicking on filter by date
        $("#date").click(function() {
            //if ($("#date").is(":checked")){
            $("#date_div").removeClass("hidden");
            $("#search-field").addClass("hidden");
            $("#date-field").removeClass("hidden");
            $("#date-field2").removeClass("hidden");
            $("#search-field2").removeClass("hidden")
            //$("#date_div").fadeIn('slow');
            //}
        });
        $("#date-field").click(function() {
            //if ($("#date").is(":checked")){
            $("#date_div").removeClass("hidden");
            $("#search-field").addClass("hidden");
            $("#date-field").removeClass("hidden");
            $("#date-field2").removeClass("hidden");
            $("#search-field2").removeClass("hidden")
            //$("#date_div").fadeIn('slow');
            //}
        });
        $("#date-field2").click(function() {
            //if ($("#date").is(":checked")){
            $("#date_div").removeClass("hidden");
            $("#search-field").addClass("hidden");
            $("#date-field").removeClass("hidden");
            $("#date-field2").removeClass("hidden");
            $("#search-field2").removeClass("hidden")
            //$("#date_div").fadeIn('slow');
            //}
        });
        ///////////////////////////////////////////////////
        $.fn.datepicker.noConflict = function() {
            $.fn.datepicker = old;
            return this;
        };
        ////////////////////////////////////////////////////
        $(function() {
            $('#date-field').datepicker({
                dateFormat : 'yy-mm-dd'
            });
        });
        //////////////////////////////////////////////////////
        $(function() {
            $('#date-field2').datepicker({
                dateFormat : 'yy-mm-dd'
            });
        });
        $('#csv').click(function() {
            console.log('works!');
            $('#csv_perpage').val($('#record').val());
            $('#csv_page').val($('li.active span').html());
            $('#csv_submit').click();
            console.log('works!');
        });
        /////////////////////////////////////////////////////////////
        $('#excel').click(function() {
            $('#excel_perpage').val($('#record').val());
            $('#excel_page').val($('li.active span').html());
            $('#excel_submit').click();
        });
    });
</script>

app/views/job_titles/new.html.erb
<div class="row">
     <div class="col-md-4 xs-3"></div>

     <div class="col-md-4 xs-6" id="form" style="border-radius: 3%; margin-top: 10%">
          <h3>New Job Title</h3>
        <%= render 'form' %>
          <!-- <%= link_to 'Show', @contact, style: 'margin-left: 50%; margin-top: -5%' %> -->
     </div>

     <div class="col-md-4 xs-3"></div>
</div>
<br><br>

app/views/job_titles/show.html.erb
<div class="row">
   <div class="col-md-3 xs-12"></div>

   <div class="col-md-6 xs-12" id="content">
     <table class="table table-striped table-condensed" >

        <h3 >Job Title Details</h3>

        <tr><td><strong>Job Title:</strong></td><td>  <%= @job_title.job_title_name %></td></tr>

    </table>

   <% if current_user.present? && current_user.role_id == 1 %>
      <%= link_to ' Edit Job Title', edit_job_title_path(@job_title), class: 'btn btn-success' %>
   <% end %>
   
    <%= link_to ' Go Back', job_titles_path, class: 'btn btn-info pull-right fa fa-angle-double-left' %>

   </div>

   <div class="col-md-3 xs-12"></div>
</div>

<!-- <p id="notice"><%= notice %></p>

<p>
  <strong>Job title name:</strong>
  <%= @job_title.job_title_name %>
</p>

<%= link_to 'Edit', edit_job_title_path(@job_title) %> |
<%= link_to 'Back', job_titles_path %> -->