config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :contacts
  get 'home/index'
  root to: 'home#index'

  resources :roles
  resources :job_titles
  resources :localities
  resources :suburbs
  resources :cities
  resources :regions
  resources :contats

  devise_scope :user do
    get '/users/sign_up' => 'users#sign_in'
  end

   get '/users' => 'users#index'

  get '/users/new' => 'users#new', :as => 'new_user'
  post 'create_user' => 'users#create', as: :create_user
  get '/users/:id/edit' => 'users#edit', :as => 'edit_user'

  get '/users/:id' => 'users#show', :as => 'user'
  delete 'users/:id' => 'users#destroy'
  patch '/users/:id' => 'users#update', :as => 'update_user'

  get       'enable_contact'    =>  'contacts#enable_contact'
  get       'disable_contact'   =>  'contacts#disable_contact'

  get       'enable_region'    =>  'regions#enable_region'
  get       'disable_region'   =>  'regions#disable_region'

  get       'enable_city'    =>  'cities#enable_city'
  get       'disable_city'   =>  'cities#disable_city'

  get       'enable_suburb'    =>  'suburbs#enable_suburb'
  get       'disable_suburb'   =>  'suburbs#disable_suburb'

  get       'enable_locality'    =>  'localities#enable_locality'
  get       'disable_locality'   =>  'localities#disable_locality'

  get       'enable_job_title'    =>  'job_titles#enable_job_title'
  get       'disable_job_title'   =>  'job_titles#disable_job_title'

  get       'enable_user'    =>  'users#enable_user'
  get       'disable_user'   =>  'users#disable_user'

  get       'enable_role'    =>  'roles#enable_role'
  get       'disable_role'   =>  'roles#disable_role'
  
  get  'city_cascade' => 'suburbs#city_cascade'
  get 'suburb_cascade' => 'localities#suburb_cascade'
  get 'city_update' => 'suburbs#city_update'
  get 'suburb_update' => 'localities#suburb_update'
  get 'suburb_contact_cascade' => 'contacts#suburb_contact_cascade'
  get 'locality_contact_cascade' => 'contacts#locality_contact_cascade'

end

app/models/region.rb
class Region < ActiveRecord::Base
  validates :region_name, presence: true

	has_many :cities, class_name: "City", foreign_key: :region_id

  def self.to_csv
    CSV.generate do |csv|
      csv << column_names ## Header values of CSV
      all.each do |cont|
        csv << cont.attributes.values_at(*column_names) ##Row values of CSV
      end
    end
  end
   acts_as_xlsx


    #   def self.phone_number_search(phone_number)
    #    phone_number = "%#{region_name}%"
    #    where('region_name LIKE ?', phone_number)
    #  end

     def self.region_name_search(region_name)
      region_name = "%#{region_name}%"
      where('region_name LIKE ?', region_name)
    end


     def self.search_date(start = nil, ended = nil)
       if start && ended
         where(created_at: "#{start} 00:00:00".."#{ended} 23:59:59")
       else
         all
       end
     end

end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_region, only: [:show, :edit, :update, :destroy]

  # GET /regions
  # GET /regions.json
  def index
    @regions = Region.all.paginate(page: params[:page], per_page: 5).order('id ASC')
    @cities = City.all.paginate(page: params[:page], per_page: 5).order('id ASC')
    @suburbs = Suburb.all.paginate(page: params[:page], per_page: 5).order('id ASC')
    @localities = Locality.all.paginate(page: params[:page], per_page: 5).order('id ASC')

        if params[:count]
         params[:count]
       else
         params[:count] = 30
       end
       if params[:page]
         page = params[:page].to_i
       else
         page = 1
       end
       if params[:per_page].present?
         perpage = params[:per_page]
       else
         perpage = 100
       end
       @per_page = params[:per_page] || Region.per_page || 30
       page = if params[:page]
                params[:page].to_i
              else
                1
               end
       per_page = 30
       offset = (page - 1) * per_page
       limit = page * per_page
       @array = *(offset...limit)

       if  params[:search_value] && params[:search_value].strip != ''
         if params[:search_param] == 'region_name'
           @regions = Region.region_name_search(params[:search_value].strip).paginate(page: params[:page], per_page: params[:count]).order('id asc')
          elsif params[:search_param] == 'phone_number'
            logger.info "We are INSIDE THE NUMBER PARAM"
            @Regions = Region.phone_number_search(params[:search_value].strip).paginate(page: params[:page], per_page: params[:count]).order('id asc')
         elsif params[:search_param] == 'date'
           start = (params["start_date"] + " " + "0:00:00")# Time.zone.parse(params["start_date"].to_s + " " + "0:00:00").utc # params["start_date"].to_s + "0:00:00"
           ended = params["end_date"] + " " + ("23:59:59") # Time.zone.parse(params["end_date"].to_s + " " + "23:59:59").utc # params["end_date"].to_s + "23:59:59"
           @regions =
             Region.search_date(start,ended).paginate(page: params[:page], per_page: params[:count]).order('id asc')

       else
          @regions = Region.paginate(page: params[:page], per_page: params[:count]).order('id desc')
          @search_json = []
         end
       end
       p "JSON ARRAY: #{@search_json}"




    respond_to do |format|
     format.html
     format.xlsx
     format.csv { send_data @regions.to_csv}
   end

  end

  # GET /regions/1
  # GET /regions/1.json
  def show
    @regions = Region.find(params[:id])
    @suburbs = Suburb.all
    @localities = Locality.all
  end

  def enable_region
      region_id=params[:id]
     if Region.update(region_id, :status => 1)
       redirect_to regions_path, notice: 'Region was successfully enabled.'
     end
  end

  def disable_region
      region_id=params[:id]
     if Region.update(region_id, :status => 0)
       redirect_to regions_path, notice: 'Region was successfully disabled.'
     end
  end



  # GET /regions/new
  def new
    @region = Region.new
  end

  # GET /regions/1/edit
  def edit
    
  end

  # POST /regions
  # POST /regions.json
  def create
    @region = Region.new(region_params)

    respond_to do |format|
      if @region.save
        format.js
        format.html { redirect_to @region, notice: 'Region was successfully created.' }
        format.json { render :show, status: :created, location: @region }
      else
        format.js {render :new}
        format.html { render :new }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regions/1
  # PATCH/PUT /regions/1.json
  def update
    respond_to do |format|
      if @region.update(region_params)
        format.html { redirect_to @region, notice: 'Region was successfully updated.' }
        format.json { render :show, status: :ok, location: @region }
      else
        format.html { render :edit }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regions/1
  # DELETE /regions/1.json
  def destroy
    @region.destroy
    respond_to do |format|
      format.html { redirect_to regions_url, notice: 'Region was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_region
      @region = Region.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def region_params
      params.require(:region).permit(:region_name, :status)
    end
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/regions/_cities.html.erb
<div class="col-md-2"></div>
<div class="col-md-8">

  <h3>Listing Cities</h3>
  <div class="table-responsive" style="border: none">
        <table class="table table-striped table-bordered table-condensed">
          <thead>
            <tr style="background: #F5FFFA;">
                <p style = 'text-align: center; font-family: tahoma; font-size: 15px;'><b>Download:</b> <%= link_to "csv", cities_path(format: "csv") %> | <%= link_to "excel", cities_path(format: "xlsx") %> </p>
            <% if current_user.present? && current_user.role_id == 1 %>
              <%= link_to 'New City', new_city_path, class: 'btn btn-default pull-right', style: 'position: fixed', :remote=> true %>
            <% end %>

              <%=form_tag cities_path, method: :get, input_html:{display:"block"} do %>

                  <div class="pull-right"><input id="city_name" type="radio" name="search_param" value="city_name" style="width: auto;" /> Filter by Region Name &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>

                 <!-- <div class="pull-right"><input id="phone_number" type="radio" name="search_param" value="phone_number" style="width: auto; " /> Filter by phone number &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div> -->


                  <input type="submit" id="search-field2" class=" hidden btn btn-primary pull-right" value="Search" style="margin-right: -10px">

                  <div class="form-inline" style="margin-left: 10px">
                       <input id="search-field" class="form-control hidden pull-right"  name="search_value" />
                  </div>

            <% end %>


              <br><br>
              <th>S/N</th>
              <th>Region</th>
              <th>City name</th>
            <% if current_user.present? && current_user.role_id == 1 %>
              <th colspan="3" style="width: 10%">Options</th>
            <% else %>
              <th style="width: 10%">Options</th>
            <% end %>
            </tr>
          </thead>

          <tbody>
            <% @cities.each do |city| %>
              <tr>
                <td><%= city.id %></td>
                <td><%= city.region.region_name %></td>
                <td><%= city.city_name %></td>
                <td><%= link_to ' Show', city, class: 'btn btn-info fa fa-eye', :remote=>true %></td>

              <% if current_user.present? && current_user.role_id == 1 %>
                <td><%= link_to ' Edit', edit_city_path(city), class: 'btn btn-default fa fa-edit', remote: true %></td>
                <!-- <td><%#= link_to ' Delete', city, method: :delete, class: 'btn btn-danger fa fa-remove' , data: { confirm: 'Are you sure?' } %></td> -->

                <td>
                  <% if city.status == false %>
                      <%= link_to 'Enable', enable_city_path(:id => city.id), :class => 'btn btn-success enable_city', remote: true %>
                      <% else city.status == true %>
                      <%= link_to 'Disable', disable_city_path(:id => city.id), :class => 'btn btn-danger disable_city', data: {confirm: 'Are you sure?'}, remote: true %>
                  <% end %>
                </td>

              <% end %>

              </tr>
            <% end %>
          </tbody>
        </table>
        <%= will_paginate @cities, renderer: BootstrapPagination::Rails, previous_label: 'Older', next_lable: 'Newer', class: 'pagination-sm', remote: true  %>

  </div>

</div>
<div class="col-md-2"></div>
<br>

<script>
    $(document).ready(function() {
        $(".radio_div div input").click(function() {
            $("#date_div").addClass("hidden");
            $("#search-field").removeClass("hidden");
            $("#narrative_div").addClass("hidden");
            //$("#date_div").fadeIn('slow');
        });
        $("#city_name").click(function() {
            if ($("#city_name").is(":checked")) {
                $("#search-field").attr("placeholder", "City Name");
                $("#search-field2").removeClass("hidden")
                $("#search-field").removeClass("hidden");
            }
        });
        ////////////////////////////////////////////////////////////////////////////
        $("#phone_number").click(function() {
            if ($("#phone_number").is(":checked")) {
                $("#search-field").attr("placeholder", "Mobile number");
                $("#date_div").addClass("hidden");
                $("#search-field").removeClass("hidden");
                $("#search-field2").removeClass("hidden")
            }
        });
        $("#recipient_number").click(function() {
            if ($("#recipient_number").is(":checked")) {
                $("#search-field").attr("placeholder", "Recipient Number");
                $("#date_div").addClass("hidden");
                $("#search-field").removeClass("hidden");
            }
        });
        //////////////////////////clicking on filter by date
        $("#date").click(function() {
            //if ($("#date").is(":checked")){
            $("#date_div").removeClass("hidden");
            $("#search-field").addClass("hidden");
            $("#date-field").removeClass("hidden");
            $("#date-field2").removeClass("hidden");
            $("#search-field2").removeClass("hidden")
            //$("#date_div").fadeIn('slow');
            //}
        });
        $("#date-field").click(function() {
            //if ($("#date").is(":checked")){
            $("#date_div").removeClass("hidden");
            $("#search-field").addClass("hidden");
            $("#date-field").removeClass("hidden");
            $("#date-field2").removeClass("hidden");
            $("#search-field2").removeClass("hidden")
            //$("#date_div").fadeIn('slow');
            //}
        });
        $("#date-field2").click(function() {
            //if ($("#date").is(":checked")){
            $("#date_div").removeClass("hidden");
            $("#search-field").addClass("hidden");
            $("#date-field").removeClass("hidden");
            $("#date-field2").removeClass("hidden");
            $("#search-field2").removeClass("hidden")
            //$("#date_div").fadeIn('slow');
            //}
        });
        ///////////////////////////////////////////////////
        // $.fn.datepicker.noConflict = function() {
        //     $.fn.datepicker = old;
        //     return this;
        // };
        ////////////////////////////////////////////////////
        // $(function() {
        //     $('#date-field').datepicker({
        //         dateFormat : 'yy-mm-dd'
        //     });
        // });
        // //////////////////////////////////////////////////////
        // $(function() {
        //     $('#date-field2').datepicker({
        //         dateFormat : 'yy-mm-dd'
        //     });
        // });
        $('#csv').click(function() {
            console.log('works!');
            $('#csv_perpage').val($('#record').val());
            $('#csv_page').val($('li.active span').html());
            $('#csv_submit').click();
            console.log('works!');
        });
        /////////////////////////////////////////////////////////////
        $('#excel').click(function() {
            $('#excel_perpage').val($('#record').val());
            $('#excel_page').val($('li.active span').html());
            $('#excel_submit').click();
        });
    });
</script>

<script type="text/javascript">
  $('')
</script>

app/views/regions/_citiy_show.js.erb
$("#cities").html("<%= escape_javascript(render(:partial=>"show")) %>");

app/views/regions/_edit.html.erb
<br>
<div class="row">
     <div class="col-md-4 xs-3"></div>

     <div class="col-md-4 xs-6" id="form" style="border-radius: 3%">
          <h3>Edit Region</h3>
          <%= render 'form' %>
          <!-- <%= link_to 'Show', @contact, style: 'margin-left: 50%; margin-top: -5%' %> -->
     </div>

     <div class="col-md-4 xs-3"></div>
</div>
<br><br>

app/views/regions/_new.html.erb
<div class="row">
     <div class="col-md-4 xs-3"></div>

     <div class="col-md-4 xs-6" id="form" style="border-radius: 3%; margin-top: 10%">
          <h3>New Region</h3>
          <%= render :partial=> 'form' %>
     </div>

     <div class="col-md-4 xs-3"></div>
</div>
<br><br>

app/views/regions/_suburbs.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<div class="col-md-2"></div>
<div class="col-md-8">
  <h3>Listing Suburbs</h3>

  <div class="table-responsive" style="border: none">
      <table class="table table-striped table-bordered table-condensed">
        <thead>
          <tr style="background: #F5FFFA;">
              <p style = 'text-align: center; font-family: tahoma; font-size: 15px;'><b>Download:</b> <%= link_to "csv", suburbs_path(format: "csv") %> | <%= link_to "excel", suburbs_path(format: "xlsx") %> </p>
          <% if current_user.present? && current_user.role_id == 1 %>
            <%= link_to 'New Suburb', new_suburb_path, class: 'btn btn-default pull-right', style: 'position: fixed', :remote=> true %>
          <% end %>

          <%=form_tag suburbs_path, method: :get, input_html:{display:"block"} do %>

          <div class="pull-right"><input id="suburb_name" type="radio" name="search_param" value="suburb_name" style="width: auto;" /> Filter by Suburb Name &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>

           <!-- <div class="pull-right"><input id="phone_number" type="radio" name="search_param" value="phone_number" style="width: auto; " /> Filter by phone number &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div> -->


          <input type="submit" id="search-field2" class=" hidden btn btn-primary pull-right" value="Search" style="margin-right: -10px">

          <div class="form-inline" style="margin-left: 10px">
             <input id="search-field" class="form-control hidden pull-right"  name="search_value" />
          </div>

          <% end %>

            <br><br>
            <th>S/N</th>
            <th>City</th>
            <th>Suburb name</th>
          <% if current_user.present? && current_user.role_id == 1 %>
            <th colspan="3" style="width: 10%">Options</th>

          <% else%>
            <th style="width: 10%">Options</th>
          <% end %>
          </tr>
        </thead>

        <tbody>
          <% @suburbs.each do |suburb| %>
            <tr>
              <td><%= suburb.id %></td>
              <td><%= suburb.city.city_name if suburb.city %></td>
              <td><%= suburb.suburb_name %></td>
              <td><%= link_to ' Show', suburb, class: 'btn btn-info fa fa-eye', remote: true %></td>

              <% if current_user.present? && current_user.role_id == 1 %>
                  <td><%= link_to ' Edit', edit_suburb_path(suburb), class: 'btn btn-default fa fa-edit', remote: true %></td>
                  
                  <td>
                    <% if suburb.status == false %>
                        <%= link_to 'Enable', enable_suburb_path(:id => suburb.id), :class => 'btn btn-success', remote: true%>
                        <% else suburb.status == true %>
                        <%= link_to 'Disable', disable_suburb_path(:id => suburb.id), :class => 'btn btn-danger',data: {confirm: 'Are you sure?'}, remote: true%>
                    <% end %>
                  </td>

              <% end %>

            </tr>
          <% end %>
        </tbody>
      </table>

      <%= will_paginate @suburbs, renderer: BootstrapPagination::Rails, previous_label: 'Older', next_lable: 'Newer', class: 'pagination-sm'  %>

  </div>

</div>
<div class="col-md-2"></div>
<br>


<script>
    $(document).ready(function() {
        $(".radio_div div input").click(function() {
            $("#date_div").addClass("hidden");
            $("#search-field").removeClass("hidden");
            $("#narrative_div").addClass("hidden");
            //$("#date_div").fadeIn('slow');
        });
        $("#suburb_name").click(function() {
            if ($("#suburb_name").is(":checked")) {
                $("#search-field").attr("placeholder", "Suburb name");
                $("#search-field2").removeClass("hidden")
                $("#search-field").removeClass("hidden");
            }
        });
        ////////////////////////////////////////////////////////////////////////////
        $("#phone_number").click(function() {
            if ($("#phone_number").is(":checked")) {
                $("#search-field").attr("placeholder", "Mobile number");
                $("#date_div").addClass("hidden");
                $("#search-field").removeClass("hidden");
                $("#search-field2").removeClass("hidden")
            }
        });
        $("#recipient_number").click(function() {
            if ($("#recipient_number").is(":checked")) {
                $("#search-field").attr("placeholder", "Recipient Number");
                $("#date_div").addClass("hidden");
                $("#search-field").removeClass("hidden");
            }
        });
        //////////////////////////clicking on filter by date
        $("#date").click(function() {
            //if ($("#date").is(":checked")){
            $("#date_div").removeClass("hidden");
            $("#search-field").addClass("hidden");
            $("#date-field").removeClass("hidden");
            $("#date-field2").removeClass("hidden");
            $("#search-field2").removeClass("hidden")
            //$("#date_div").fadeIn('slow');
            //}
        });
        $("#date-field").click(function() {
            //if ($("#date").is(":checked")){
            $("#date_div").removeClass("hidden");
            $("#search-field").addClass("hidden");
            $("#date-field").removeClass("hidden");
            $("#date-field2").removeClass("hidden");
            $("#search-field2").removeClass("hidden")
            //$("#date_div").fadeIn('slow');
            //}
        });
        $("#date-field2").click(function() {
            //if ($("#date").is(":checked")){
            $("#date_div").removeClass("hidden");
            $("#search-field").addClass("hidden");
            $("#date-field").removeClass("hidden");
            $("#date-field2").removeClass("hidden");
            $("#search-field2").removeClass("hidden")
            //$("#date_div").fadeIn('slow');
            //}
        });
        ///////////////////////////////////////////////////
        // $.fn.datepicker.noConflict = function() {
        //     $.fn.datepicker = old;
        //     return this;
        // };
        // ////////////////////////////////////////////////////
        // $(function() {
        //     $('#date-field').datepicker({
        //         dateFormat : 'yy-mm-dd'
        //     });
        // });
        // //////////////////////////////////////////////////////
        // $(function() {
        //     $('#date-field2').datepicker({
        //         dateFormat : 'yy-mm-dd'
        //     });
        // });
        $('#csv').click(function() {
            console.log('works!');
            $('#csv_perpage').val($('#record').val());
            $('#csv_page').val($('li.active span').html());
            $('#csv_submit').click();
            console.log('works!');
        });
        /////////////////////////////////////////////////////////////
        $('#excel').click(function() {
            $('#excel_perpage').val($('#record').val());
            $('#excel_page').val($('li.active span').html());
            $('#excel_submit').click();
        });
    });
</script>

app/views/regions/_suburbs_form.html.erb
<%= simple_form_for(@suburb) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :city_id, collection: @cities, label_method: :city_name, value_method: :id %>
    <%= f.input :suburb_name %>
      <%= f.input :status, :as=> :hidden, input_html: {value: 1 } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn-success' %>
    <%= link_to ' Go Back', regions_path, class: 'pull-right btn btn-info fa fa-angle-double-left' %>
  </div>
<% end %>

app/views/regions/cities.js.erb
$("#cities").html("<%= escape_javascript(render(:partial=>"regions_index/cities")) %>");

app/views/regions/create.js.erb
$("#regions_index").html("<%= escape_javascript(render(:partial =>"show")) %>");

app/views/regions/edit.js.erb
$("#regions_index").html("<%= escape_javascript(render(:partial=>"edit")) %>");

app/views/regions/localities.js.erb
$("#localities").html("<%= escape_javascript(render(:partial=>"regions_index/localities")) %>");

app/views/regions/new.html.erb
<div class="row">
     <div class="col-md-4 xs-3"></div>

     <div class="col-md-4 xs-6" id="form" style="border-radius: 3%; margin-top: 10%">
          <h3>New Region</h3>
          <%= render 'form' %>

          <!-- <%= link_to 'Show', @contact, style: 'margin-left: 50%; margin-top: -5%' %> -->
     </div>

     <div class="col-md-4 xs-3"></div>
</div>
<br><br>

app/views/regions/new.js.erb
$("#regions_index").html("<%= escape_javascript(render(:partial=>"new")) %>");

app/views/regions/show.html.erb
<div class="row">
   <div class="col-md-3 xs-12"></div>

   <div class="col-md-6 xs-12" id="content">
     <table class="table table-striped table-condensed" >

        <h3 >Region Details</h3>

        <tr><td><strong>Region Name:</strong></td><td><%= @region.region_name %></td></tr>

    </table>


    <% if current_user.present? && current_user.role_id == 1 %>
       <%= link_to ' Edit Region', edit_region_path(@region), class: 'btn btn-success' %>
    <% end %>
    <%= link_to ' Go Back', regions_path, class: 'btn btn-info pull-right fa fa-angle-double-left' %>

   </div>

   <div class="col-md-3 xs-12"></div>
</div>

<!-- <p id="notice"><%= notice %></p>

<p>
  <strong>Region name:</strong>
  <%= @region.region_name %>
</p>

<%= link_to 'Edit', edit_region_path(@region) %> |
<%= link_to 'Back', regions_path %> -->

app/views/regions/suburbs.js.erb
$("#suburbs").html("<%= escape_javascript(render(:partial=>"regions_index/suburbs")) %>");